-- ============================================================================
-- INITIAL DATA FOR CRUDCLOUD
-- ============================================================================
-- This file is intentionally left empty to keep the database clean
-- All data is managed via Flyway migrations in db/migration/ directory
-- Test data can be inserted manually via API endpoints or SQL scripts