package com.crudzaso.CrudCloud.dto.request;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Request DTO for GitHub OAuth authentication.
 * Contains the authorization code or token generated by GitHub on the frontend.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class GitHubOAuthRequest {
    @NotBlank(message = "GitHub token is required")
    private String token;
}
