package com.crudzaso.CrudCloud.dto.request;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Request DTO for Google OAuth authentication.
 * Contains the JWT token generated by Google on the frontend.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class GoogleOAuthRequest {
    @NotBlank(message = "Google token is required")
    private String token;
}
